### ISSUE TITLE
About IMUSE

### ISSUE THREAD

**Issue by nikofan18** [nju-websoft/OpenEA#11]
Hello, I am looking to get the value of "λ" (trained by the bivariate regression model, as mentioned in original paper of IMUSE). Could you please confirm that this happens and if yes, where ?

Thank you in advance

**Comment by sunzequn** [comment]
Hi, 

Thanks for your interest in our work. 
As the authors of IMUSE did not provide the source code, we try our best to implement it based on our understandings of the paper and its performance on our datasets. Qingheng is the author of the code. I will double-check this issue with him and let you know as soon as possible. 

Best,
Zequn Sun

**Comment by nikofan18** [comment]
Thank you very much for your response
