### ISSUE TITLE
Problem on installing graph tool 

### ISSUE THREAD

**Issue by AronWater** [nju-websoft/OpenEA#14]
PackagesNotFoundError: The following packages are not available from current channels:

  - graph-tool==2.29

**Comment by sunzequn** [comment]
Hi,

Thanks for your interest in our work. 
I have just tried to install graph-tool==2.29 and it worked well (please see the following screenshots). 

![image](https://user-images.githubusercontent.com/5676248/98889262-9405b200-24d4-11eb-8f79-25d187ff3636.png)
![image](https://user-images.githubusercontent.com/5676248/98889218-7c2e2e00-24d4-11eb-8c19-26747e52e878.png)

You can take a try with the following script:
`conda install -c conda-forge graph-tool==2.29`

**Comment by AronWater** [comment]
problem found,

https://anaconda.org/conda-forge/graph-tool,

this is only available in Linux or osx

**Comment by sty945** [comment]
I solved this problem follow by this:

```
conda install mamba -c conda-forge
mamba install graph-tool --channel conda-forge
```
