### ISSUE TITLE
有一些模型在D_Y数据集上复现的精度达到了0.99

### ISSUE THREAD

**Issue by karlind** [nju-websoft/OpenEA#2]
有一些模型，比如`MultiKE`，在`D_Y_15K_V1`上性能达到了0.99。配置文件没有改动，运行命令如下：
```
python main_from_args.py ./args/multike_args_15K.json D_Y_15K_V1 721_5fold/1/
```
请问这有可能是哪里出问题了呢？

**Comment by sunzequn** [comment]
你好，感谢你对我们工作的关注。我们检查了一下，由于之前对数据集进行了重命名，造成代码里面数据预处理部分有一个小bug，现在已经修复了。我复现了一下MultiKE在D_Y_15K_V1的效果，和之前一样。谢谢！

**Comment by karlind** [comment]
感谢回复，问题已经解决。非常棒的工作

**Comment by LiuYuLOL** [comment]
Hi, 好像换成`BootEA_DBP_YG_100K`这个数据集也有类似的问题？具体情况如下：

- Framework: OpenEA
- Approach: Multi-KE
- Dataset: BootEA_DBP_YG_100K/631

```
nv valid results:
quick results: hits@[1, 5, 10, 50] = [ 99.99 100.   100.   100.  ]%, time = 12.446 s 

```

**Comment by sunzequn** [comment]
你好，

感谢你对我们实体对齐工作的关注！

这个问题目前比较清晰了，是因为很多开源的图谱都是基于Wikipedia抽取的，比如DBpedia和YAGO，它们会直接使用Wikipedia页面标题作为实体的local name，导致在这些图谱中，对齐的实体往往具有相同的local name甚至label。所以我们**不建议使用local names作为feature去进行实体对齐**，因为它不具备普遍性，可能在跨语言尤其是小语种跨语言，或者name不可获得（比如Wikidata或Freebase等）的情况下，利用name的方法可能就不work了。

我们openEA的工作其实委婉提到了这个事情，后来工作如TKDE的[综述论文](https://ieeexplore.ieee.org/document/9174835/)和EMNLP2020的一篇[论文](https://www.aclweb.org/anthology/2020.emnlp-main.515.pdf)都注意到了这个name bias问题，所以，不建议使用name作为核心feature去做实体对齐，如果使用，可以在DBP15K或者你可以尝试构造更加low-resource的数据集来测试，且建议给ablation study说明不用name时候的性能表现如何。

我在构造OpenEA数据集的时候，考虑到这个问题了，曾把local name仿照Wikidata或者Freebase的方式encode一下，但是考虑为了支持之前的一些方法，以及数据可溯源，就没有使用这个版本。我后面考虑放出来这个版本，供attribute-based方法去使用。

**Comment by MrYxJ** [comment]
你好,
正如您所说，之前的数据集里实体的名称在对齐过程中起到很大作用，同时论文里结果是datasets1.1的版本跑出来，最新的dataset2.0弱化名称，是在attribue triples里去掉很多name的信息。所以我用dataset2.0跑出很多嵌入实体名称的模型对齐的效果下降不少，比如: rdgcn,multiKE，这是正常的吗？

**Comment by sunzequn** [comment]
你好，这个结果是意料之中的。

现在对于name的事情，我的看法是，可以使用name作为feature，但是要选好数据集，比如跨语言数据集，比如异质性大的数据集，此外，要做好公平对比，比如做好ablation study，看看不用name的话性能怎么样，此外，要和同样使用name的方法去比较，不能单纯以name作为trick。其实，只要是做了公平比较的，数据集和实验可以正确反映出真实性能的，我觉得用不用name都不是问题。

**Comment by sunzequn** [comment]
> 你好,
> 正如您所说，之前的数据集里实体的名称在对齐过程中起到很大作用，同时论文里结果是datasets1.1的版本跑出来，最新的dataset2.0弱化名称，是在attribue triples里去掉很多name的信息。所以我用dataset2.0跑出很多嵌入实体名称的模型对齐的效果下降不少，比如: rdgcn,multiKE，这是正常的吗？

你好，这个结果是意料之中的。

现在对于name的事情，我的看法是，可以使用name作为feature，但是要选好数据集，比如跨语言数据集，比如异质性大的数据集，此外，要做好公平对比，比如做好ablation study，看看不用name的话性能怎么样，此外，要和同样使用name的方法去比较，不能单纯以name作为trick。其实，只要是做了公平比较的，数据集和实验可以正确反映出真实性能的，我觉得用不用name都不是问题。
