### ISSUE TITLE
Can you give me the description of your dataset?

### ISSUE THREAD

**Issue by wxl1351641822** [nju-websoft/OpenEA#24]
Can you give me the description of your dataset?and DWY100K?

**Comment by sunzequn** [comment]
You can refer to [https://github.com/nju-websoft/OpenEA#dataset-description](https://github.com/nju-websoft/OpenEA#dataset-description) for a description of the OpenEA dataset.

The description for DWY100K is available at [https://github.com/nju-websoft/BootEA](https://github.com/nju-websoft/BootEA).

Thanks for your interest in our work!

Zequn
