### ISSUE TITLE
About the Knowing the No-match paper.

### ISSUE THREAD

**Issue by WatsonWangZh** [nju-websoft/OpenEA#27]
Have you upload the DBP2.0 dataset and relevant resource?

**Comment by WatsonWangZh** [comment]
@sunzequn

**Comment by sunzequn** [comment]
Hi,

Not yet.

I've been very busy recently and I need some time to clear the code and integrate it into OpenEA. 

I plan to upload the DBP2.0 dataset in the next few days and upload the code in the next few weeks.

Thanks for your interest in our work!

Zequn

**Comment by whu2015** [comment]
The dataset and source code have been uploaded.
