### ISSUE TITLE
请问作者这个项目在哪个运行环境下好？windows还是Linux呢？

### ISSUE THREAD

**Issue by Feny321** [nju-websoft/OpenEA#29]
我利用pycharm运行这个项目，总会报一下错误，无法解决，想知道作者是在哪个环境下运行的呢？谢谢

**Comment by sunzequn** [comment]
你好，

感谢关注我们的工作。

Mac和Linux上应该都可以运行。Windows上面可能有的包无法安装导致无法运行。

**Comment by Feny321** [comment]
好的，感谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nju-websoft/OpenEA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nju-websoft/OpenEA] 请问作者这个项目在哪个运行环境下好？windows还是Linux呢？ (#29)





 
你好，
 
感谢关注我们的工作。
 
Mac和Linux上应该都可以运行。Windows上面可能有的包无法安装导致无法运行。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kongshengjie** [comment]
请问一下这个项目支持在windows 10环境下运行吗
