### ISSUE TITLE
无法复现MultiKE模型在各个子数据集上的结果

### ISSUE THREAD

**Issue by HUSTLyn** [nju-websoft/OpenEA#33]
您好，我尝试复现了几个模型在数据集上的效果。目前MultiKE模型在各个子数据集上的Hit@1均只有20+。我尝试了跟换TensorFlow版本（1.12，1.15），均没有效果。
请问我是否遗漏了什么细节。

BTW：MultiKE使用的name embedding是word2vec，用在法语和德语是是否合理呢？

**Comment by sunzequn** [comment]
你好，感谢你对我们工作的关注。你可能用错数据集了，复现论文里面的结果，需要1.0或者1.1版本的数据集。关于word2vec，因为法语德语和英语同源，所以普通的word embeddings也够用。当然，你也可以尝试其他预训练的embeddings.

**Comment by HUSTLyn** [comment]
> 

感谢光速解答！
