### ISSUE TITLE
请问dataset文件夹在哪

### ISSUE THREAD

**Issue by JLei67** [nju-websoft/OpenEA#34]
python main_from_args.py ./args/bootea_args_15K.json D_W_15K_V1 721_5fold/1/
给的例子里面用到了datase文件夹     "training_data": "../../datasets/"  下的D_W_15K_V1数据集，但是现在没有找到。

**Comment by jiaaayiii** [comment]
需要到作者提供的网盘地址下载。readme里有链接。
