### ISSUE TITLE
Hosting datasets at zenodo or figshare

### ISSUE THREAD

**Issue by dobraczka** [nju-websoft/OpenEA#35]
Thank you for this nice library. I was wondering if it would be possible to put the datasets in a more stable location e.g. Zenodo or FigShare. Zenodo for example enables versioning, which as seen in the original benchmark datasets is a common occurrence.

**Comment by sunzequn** [comment]
Hi,

Thanks for your suggestion. We have uploaded the dataset to [figshare](https://figshare.com/articles/dataset/OpenEA_dataset_v1_1/19258760/3).
