### ISSUE TITLE
Is it possible to have a PyTorch vesion OpenEA?

### ISSUE THREAD

**Issue by LiuYuLOL** [nju-websoft/OpenEA#5]
Hi,

Thanks for the great work for Entity Alignment. Just wondering is there any possibility to publish a PyTorch version as the current version of TensorFlow is hard to debug during the session is running.

Cheers,
Yu

**Comment by sunzequn** [comment]
Thanks for your suggestion, and we will consider it. Currently, you can use https://github.com/THU-KEG/EAkit, a PyTorch-based toolkit for entity alignment.
