### ISSUE TITLE
实体对齐后的步骤

### ISSUE THREAD

**Issue by missyoudaisy** [nju-websoft/OpenEA#50]
老师，您好~
请问求出对齐的实体后，怎么将两个实体各自的子知识图谱进行融合呢？如何合并相同的属性和关系，构成一个新的融合的知识图谱？

**Comment by sunzequn** [comment]
同学你好，感谢你对我们工作的关注，很抱歉回复晚了。

你可以搜一下多源数据融合、知识验真、冲突消解等相关文章，也可以参考胡老师的tutorial[《知识图谱融合方法》](https://github.com/nju-websoft/KnowledgeGraphFusion)第五章的内容。

**Comment by missyoudaisy** [comment]
> 同学你好，感谢你对我们工作的关注，很抱歉回复晚了。
> 
> 你可以搜一下多源数据融合、知识验真、冲突消解等相关文章，也可以参考胡老师的tutorial[《知识图谱融合方法》](https://github.com/nju-websoft/KnowledgeGraphFusion)第五章的内容。

谢谢老师的回复，我尝试一下~
