### ISSUE TITLE
something about the output

### ISSUE THREAD

**Issue by keenpray** [nju-websoft/OpenEA#6]
I am a beginner in this research direction, thank you for your patience to answer my doubts.

I am confused about the alignment_results_12 in output/results. Is it the paired entity id after KG1 and KG2 are aligned? 
I checked some of the ids in alignment_results_12 and found that there are differences between the paired entities

**Comment by sunzequn** [comment]
Thanks for your interest in our work! The output file `alignment_results_12` contains the predicted Hits@1 alignment pairs of the approach. It is not the ids of entities. It is the index of entities in the test list such as `self.kgs.test_entities1`. For the sake of simplicity, I will update the code to let the output file use entity ids.

**Comment by sunzequn** [comment]
I have updated the code. Please use the latest version.

**Comment by keenpray** [comment]
It is very helpful to me. Thx~
