### ISSUE TITLE
about the implementation of RDGCN

### ISSUE THREAD

**Issue by JadeXIN** [nju-websoft/OpenEA#7]
Hi,

I am not quite familiar with TensorFlow, but I think there may be an error in the implementation of RDGCN. In file src\openea\approaches\rdgcn.py method training, you execute the negative sampling outside the epoch, so the negative samples unchanged, along with the feeddict. But I refer to the original code of RDGCN, they perform negative sampling every 10 epochs. Is that the same execution or your code made a mistake? I am not sure of my opinion. So hope you can solve my problem.

Many thanks

**Comment by sunzequn** [comment]
Hi,

Thank you very much for pointing out this issue. I have checked the running logs and our commit history, and find that the negative sampling code in the training epoch was commented out by mistake during the follow-up experiments. I have fixed the bug. Please check out the latest version. After my testing, I find it has no obvious effect on the main experimental results and conclusions. We will update the detailed results if necessary in the next version.
